### ISSUE TITLE
http://localhost:4200 is not an accepted origin.

### ISSUE THREAD

**Issue by GraphicalDot** [miguelgrinberg/python-socketio#329]
My Angular code to connect to socket is 

```

const SERVER_URL = 'http://localhost:8000';


export enum Event {
    CONNECT = 'connect',
    DISCONNECT = 'disconnect'
}
@Injectable()
export class SocketService {
    socket: SocketIOClient.Socket;


    public initSocket(): void {
        //this.socket = socketIo.connect(SERVER_URL);
        this.socket = socketIo.connect(SERVER_URL);
    }

    public send(message: any): void {
        this.socket.emit('message', message);
    }

    public onMessage(): Observable<any> {
        return new Observable<any>(observer => {
            this.socket.on('message', (data: any) => observer.next(data));
        });
    }

    public onEvent(event: Event): Observable<any> {
        return new Observable<Event>(observer => {
            this.socket.on(event, () => observer.next());
        });
    }
}
```

The backend code is on sanic with python-socketio, I have added all the options in documentation to enable proper cors .

```
sio = socketio.AsyncServer(async_mode='sanic', cors_allowed_origins=[])

app = Sanic(__name__)


# app.config['CORS_AUTOMATIC_OPTIONS'] = True
# app.config['CORS_SUPPORTS_CREDENTIALS'] = True
#app.config['CORS_ALLOW_CREDENTIALS'] = True

##cors = CORS(app, resources={r"*": {"origins": "*"}})
app.config['CORS_SUPPORTS_CREDENTIALS'] = True

CORS(app, resources={r"/*": {"origins": "*"}}, automatic_options=True)

logging.getLogger('sanic_cors').level = logging.DEBUG

sio.attach(app)
```
but i am still getting this error,

```
GET http://localhost:8000/socket.io/?EIO=3&transport=polling&t=MnIDQ5q 400 (Bad Request)
```

**Comment by miguelgrinberg** [comment]
A fix is in progress. Would you be able to test the current master branch of python-engineio? Let me know if the problem is solved.

**Comment by miguelgrinberg** [comment]
Fixed in python-engineio 3.9.1.

**Comment by GraphicalDot** [comment]
Not solved , 

My python-engineio version is python-engineio==3.9.1
python-socketio==4.3.0

**Comment by miguelgrinberg** [comment]
Please provide the request and response headers that you are getting on the connection. You can get them from your browser's network panel.

**Comment by GraphicalDot** [comment]
General
```
Request URL: http://localhost:8000/socket.io/?EIO=3&transport=polling&t=MnIkFtr
Request Method: GET
Status Code: 400 Bad Request
Remote Address: 127.0.0.1:8000
Referrer Policy: no-referrer-when-downgrade
```


Request headers:
```
GET /socket.io/?EIO=3&transport=polling&t=MnIkFtr HTTP/1.1
Host: localhost:8000
Connection: keep-alive
Accept: */*
Origin: http://localhost:4200
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) angular-electron/5.1.0 Chrome/69.0.3497.106 Electron/4.0.0 Safari/537.36
Referer: http://localhost:4200/
Accept-Encoding: gzip, deflate, br
Accept-Language: en-GB
``` 

Response headers
```
HTTP/1.1 400 Bad Request
Connection: keep-alive
Keep-Alive: 5
Access-Control-Allow-Origin: http://localhost:4200
Access-Control-Allow-Credentials: true
Vary: Origin
Content-Length: 11
Content-Type: text/plain
```

**Comment by miguelgrinberg** [comment]
Thanks. Can I ask you to test the master branch of python-engineio and report if the problem is finally solved?

**Comment by GraphicalDot** [comment]
i installed python-engineio from github repo 
```
Traceback (most recent call last):
  File "application.py", line 39, in <module>
    from data_sources import DATASOURCES_BP
  File "/home/feynman/Programs/datapod-backend-layer/Application/data_sources/__init__.py", line 7, in <module>
    from .takeout  import TAKEOUT_BP
  File "/home/feynman/Programs/datapod-backend-layer/Application/data_sources/takeout/__init__.py", line 5, in <module>
    from .api import TAKEOUT_BP
  File "/home/feynman/Programs/datapod-backend-layer/Application/data_sources/takeout/api.py", line 7, in <module>
    from .parse_emails import TakeoutEmails
  File "/home/feynman/Programs/datapod-backend-layer/Application/data_sources/takeout/parse_emails.py", line 28, in <module>
    from sockets.sockets import broadcast
  File "/home/feynman/Programs/datapod-backend-layer/Application/sockets/sockets.py", line 3, in <module>
    import socketio
  File "/home/feynman/Programs/datapod-backend-layer/lib/python3.7/site-packages/socketio/__init__.py", line 3, in <module>
    from .client import Client
  File "/home/feynman/Programs/datapod-backend-layer/lib/python3.7/site-packages/socketio/client.py", line 6, in <module>
    import engineio
  File "/home/feynman/Programs/datapod-backend-layer/lib/python3.7/site-packages/python_engineio-3.9.1-py3.7.egg/engineio/__init__.py", line 9, in <module>
    from .async_drivers.asgi import ASGIApp
ModuleNotFoundError: No module named 'engineio.async_drivers'
```

Getting this error

**Comment by miguelgrinberg** [comment]
@GraphicalDot how did you do this installation? You appear to be missing some components of the package.

**Comment by GraphicalDot** [comment]
python setup.py install

**Comment by miguelgrinberg** [comment]
Can you check your virtualenv? The error says there is no `engineio.async_drivers` directory there., but that should have been part of the installation. This has nothing to do with the problem we are discussing, by the way, something in your installation is just missing.

**Comment by GraphicalDot** [comment]
pip install git+https://github.com/miguelgrinberg/python-engineio.git

still same error, what needs to be checked in virtualenv?

**Comment by miguelgrinberg** [comment]
Well, you should have a `engineio/async_drivers` directory in the site-packages folder of your virtualenv. I don't understand why that is missing.

**Comment by GraphicalDot** [comment]
I ha ve checked, no directory for engineio/async_drivers in site-packages dir.
I have re-spawned the virtualenv with ptyhon3.7,  Same error.

**Comment by miguelgrinberg** [comment]
Try this. Clone the repo, then from the top-level directory do ths:

    pip install -e .

(note the dot at the end)

**Comment by GraphicalDot** [comment]
Successfully installed 
Entries in Pip freeze
```
python-dotenv==0.10.3
-e git+https://github.com/miguelgrinberg/python-engineio.git@502bf4eeb6f33945afe5d58975557748f3df1d14#egg=python_engineio
python-jose==3.0.1
```

But still facing the same issue of cors.

**Comment by miguelgrinberg** [comment]
@GraphicalDot you haven't installed like I asked you. The version that you installed is the 3.9.1 release. Note that SHA which is `502bf4eeb6f33945afe5d58975557748f3df1d14`. That matches the release, not the tip of master.

**Comment by GraphicalDot** [comment]
Great!!...

The socket is now connected ...
Thanks a lot Miguel..

```
-e git+https://github.com/miguelgrinberg/python-engineio.git@e4163b64f3482d2d97dccf813a880cb6ad088533#egg=python_engineio
```

**Comment by miguelgrinberg** [comment]
Thanks. Released as 3.9.2.
