### ISSUE TITLE
AsyncClient does not notice it got disconnected from aiohttp server

### ISSUE THREAD

**Issue by ydylla** [miguelgrinberg/python-socketio#459]
Hi,
I think the AsyncClient has a problem receiving disconnect events from an aiohttp server.
When my server is shutting down it sends disconnects to all connected clients. My clients periodically check `sio.connected` to see if they need to reconnect. This works fine when the connection is killed/lost without disconnect events. But when the server goes away after sending a disconnect the clients get stuck because `sio.connected` is still `True` also their disconnect event handler is not called.

I wrote the following test client which can be run against the [aiohttp example server](https://github.com/miguelgrinberg/python-socketio/blob/master/examples/server/aiohttp/app.py).
The only change I made was to upgrade the aiohttp dependency to version 3.6.2 in the requirements.txt.

The test client also shows that the aiohttp WebSocketResponse was received and closed successfully.
As a workaround I currently check `sio.eio.ws.closed` to determine if the client was disconnected.

```python
import asyncio
import socketio

sio = socketio.AsyncClient()

@sio.event
async def connect():
    print("connected to server")

    # not sure why this prints False, should be True??
    print(f"sio.connected: {sio.connected}")
    # this will print None because a WebsocketResponse does not exist at this point in time
    print(f"sio.eio.ws.closed: {sio.eio.ws.closed if sio.eio.ws else sio.eio.ws}")

    print("sending disconnect_request")
    await sio.send("disconnect_request")

@sio.event
async def disconnect():
    print("got disconnect from server")

async def main():
    await sio.connect("http://127.0.0.1:8080")
    for i in range(0, 4):
        await asyncio.sleep(1)
        print(f"sio.connected: {sio.connected}")
        print(f"sio.eio.ws.closed: {sio.eio.ws.closed}")
    await sio.disconnect() # prints warning from aiohttp "websocket connection is closing."

if __name__ == "__main__":
    asyncio.run(main())
```

**Comment by ydylla** [comment]
This could also be related to #447, but I was not sure thus I opened a new issue.

**Comment by miguelgrinberg** [comment]
Aside from the potential bug you have found, why are you trying to reconnect your client, given that the client has reconnect functionality of its own?

**Comment by ydylla** [comment]
The manual reconnect has multiple reasons.
The clients are also very long lived and have a main loop, because its a master/slave setup.
So the connection checking was easy to implement, also I wanted to cover situations where slaves start before the server.
But the main reason is I migrated from another websocket client which did not auto reconnect, so the code already existed :smile:

**Comment by miguelgrinberg** [comment]
@ydylla this:

    await sio.send("disconnect_request")

should be:

    await sio.emit("disconnect_request")

And then your client works fine, as far as I can see. Note that there was another unrelated disconnect bugfix that I just committed, so you may want to use the master branch of package python-engineio instead of the official release if that still gives you trouble.

Also as a suggestion, turn off reconnects in this package if you plan on doing this yourself.

**Comment by ydylla** [comment]
Thanks that you looked into it.

You are right my test client was flawed :facepalm: Sorry for that.
Sadly your fix from the master branch did not resolve the issue for me.

I tried a couple of hours to create a simple example to reproduce the issue but without success.
So its likely that something else in my code is causing it. But currently I don't want to invest more time into isolating the problem. So feel free to close this issue, I will use my workaround for now, and come back to it when I have more time.

Activating or deactivating the auto reconnect did not made a difference.

Here is some more context, just for completeness:
* Windows 7
* Python 3.7.5 with aiohttp==3.6.2 & python-socketio==4.5.1
* Non default event loop for subprocess support
```python
# https://docs.python.org/3/library/asyncio-platforms.html#asyncio-windows-subprocess
asyncio.set_event_loop_policy(asyncio.WindowsProactorEventLoopPolicy())
```

A log with a broken connection, that does not recover (despite active auto reconnect).
My manual checking prints the values of `sio.connected` & `sio.eio.ws.closed` every 30 seconds.
The message contents where removed by me.
<details>
  <summary>Click here for log</summary>

```
10-04-2020 18:14:46 debug   [MainThread] proactor_events.__init__ --- Using proactor: IocpProactor
10-04-2020 18:14:46 info    [MainThread] __init__.main_loop --- Started main loop
10-04-2020 18:14:46 debug   [MainThread] __init__.tick --- sio.connected: False
10-04-2020 18:14:46 debug   [MainThread] __init__.tick --- sio.eio.ws.closed: None
10-04-2020 18:14:46 info    [MainThread] __init__.connect --- Connecting to master http://127.0.0.1:7000
10-04-2020 18:14:46 info    [MainThread] asyncio_client._connect_websocket --- Attempting WebSocket connection to ws://127.0.0.1:7000/socket.io/?transport=websocke
t&EIO=3
======== Running on http://0.0.0.0:7001 ========
(Press CTRL+C to quit)
10-04-2020 18:14:46 info    [MainThread] asyncio_client._connect_websocket --- WebSocket connection accepted with {'sid': '7be09b1b6e554032ad73b43f7f448670', 'upgrades': [], 'pingTimeout': 60000, 'pingInterval': 25000}
10-04-2020 18:14:46 info    [MainThread] asyncio_client._handle_eio_connect --- Engine.IO connection established
10-04-2020 18:14:46 info    [MainThread] __init__.tick --- checked
10-04-2020 18:14:46 info    [MainThread] asyncio_client._send_packet --- Sending packet PING data None
10-04-2020 18:14:46 info    [MainThread] asyncio_client._receive_packet --- Received packet MESSAGE data 0
10-04-2020 18:14:46 info    [MainThread] asyncio_client._handle_connect --- Namespace / is connected
10-04-2020 18:14:46 debug   [MainThread] __init__.on_connect --- connect
10-04-2020 18:14:46 info    [MainThread] asyncio_client.emit --- Emitting event "message" [/]
10-04-2020 18:14:46 info    [MainThread] asyncio_client._send_packet --- Sending packet MESSAGE data 2["message","{..}"]
10-04-2020 18:14:46 info    [MainThread] asyncio_client._receive_packet --- Received packet PONG data None
10-04-2020 18:14:46 info    [MainThread] asyncio_client._receive_packet --- Received packet MESSAGE data 2["message","{..}"]
10-04-2020 18:14:46 info    [MainThread] asyncio_client._handle_event --- Received event "message" [/]
10-04-2020 18:14:46 info    [MainThread] asyncio_client.emit --- Emitting event "message" [/]
10-04-2020 18:14:46 info    [MainThread] asyncio_client._send_packet --- Sending packet MESSAGE data 2["message","{..}"]
10-04-2020 18:14:46 info    [MainThread] __init__.on_message --- Send hashed nonce to master
10-04-2020 18:14:46 info    [MainThread] protocol._work --- Handshake successful
10-04-2020 18:14:46 info    [MainThread] asyncio_client._receive_packet --- Received packet MESSAGE data 2["message","{..}"]
10-04-2020 18:14:46 info    [MainThread] asyncio_client._handle_event --- Received event "message" [/]
10-04-2020 18:14:46 info    [MainThread] asyncio_client.emit --- Emitting event "message" [/]
10-04-2020 18:14:46 info    [MainThread] asyncio_client._send_packet --- Sending packet MESSAGE data 2["message","{..}"]
10-04-2020 18:14:48 info    [MainThread] asyncio_client._receive_packet --- Received packet MESSAGE data 2["message","{..}"]
10-04-2020 18:14:48 info    [MainThread] asyncio_client._receive_packet --- Received packet MESSAGE data 2["message","{..}"]
10-04-2020 18:14:49 info    [MainThread] asyncio_client.emit --- Emitting event "message" [/]
10-04-2020 18:14:49 info    [MainThread] asyncio_client._send_packet --- Sending packet MESSAGE data 2["message","{..}"]
10-04-2020 18:14:49 info    [MainThread] asyncio_client.emit --- Emitting event "message" [/]
10-04-2020 18:14:49 info    [MainThread] asyncio_client._send_packet --- Sending packet MESSAGE data 2["message","{..}"]
10-04-2020 18:14:49 info    [MainThread] asyncio_client.emit --- Emitting event "message" [/]
10-04-2020 18:14:49 info    [MainThread] asyncio_client._send_packet --- Sending packet MESSAGE data 2["message","{..}"]
10-04-2020 18:14:49 info    [MainThread] asyncio_client.emit --- Emitting event "message" [/]
10-04-2020 18:14:49 info    [MainThread] asyncio_client._send_packet --- Sending packet MESSAGE data 2["message","{..}"]
10-04-2020 18:14:49 info    [MainThread] asyncio_client.emit --- Emitting event "message" [/]
10-04-2020 18:14:49 info    [MainThread] asyncio_client._send_packet --- Sending packet MESSAGE data 2["message","{..}"]
10-04-2020 18:14:49 info    [MainThread] asyncio_client.emit --- Emitting event "message" [/]
10-04-2020 18:14:49 info    [MainThread] asyncio_client._send_packet --- Sending packet MESSAGE data 2["message","{..}"]
10-04-2020 18:14:49 info    [MainThread] asyncio_client.emit --- Emitting event "message" [/]
10-04-2020 18:14:49 info    [MainThread] asyncio_client._send_packet --- Sending packet MESSAGE data 2["message","{..}"]
10-04-2020 18:14:49 info    [MainThread] asyncio_client.emit --- Emitting event "message" [/]
10-04-2020 18:14:49 info    [MainThread] asyncio_client._send_packet --- Sending packet MESSAGE data 2["message","{..}"]
10-04-2020 18:14:49 info    [MainThread] asyncio_client.emit --- Emitting event "message" [/]
10-04-2020 18:14:49 info    [MainThread] asyncio_client._send_packet --- Sending packet MESSAGE data 2["message","{..}"]
10-04-2020 18:14:49 info    [MainThread] asyncio_client.emit --- Emitting event "message" [/]
10-04-2020 18:14:49 info    [MainThread] asyncio_client._send_packet --- Sending packet MESSAGE data 2["message","{..}"]
10-04-2020 18:14:49 info    [MainThread] asyncio_client.emit --- Emitting event "message" [/]
10-04-2020 18:14:49 info    [MainThread] asyncio_client._send_packet --- Sending packet MESSAGE data 2["message","{..}"]
10-04-2020 18:14:49 info    [MainThread] asyncio_client.emit --- Emitting event "message" [/]
10-04-2020 18:14:49 info    [MainThread] asyncio_client._send_packet --- Sending packet MESSAGE data 2["message","{..}"]
10-04-2020 18:14:49 info    [MainThread] asyncio_client.emit --- Emitting event "message" [/]
10-04-2020 18:14:49 info    [MainThread] asyncio_client._send_packet --- Sending packet MESSAGE data 2["message","{..}"]
10-04-2020 18:14:49 info    [MainThread] asyncio_client.emit --- Emitting event "message" [/]
10-04-2020 18:14:49 info    [MainThread] asyncio_client._send_packet --- Sending packet MESSAGE data 2["message","{..}"]
10-04-2020 18:14:49 info    [MainThread] asyncio_client.emit --- Emitting event "message" [/]
10-04-2020 18:14:49 info    [MainThread] asyncio_client._send_packet --- Sending packet MESSAGE data 2["message","{..}"]
10-04-2020 18:15:06 info    [MainThread] asyncio_client._receive_packet --- Received packet MESSAGE data 2["message","{..}"]
10-04-2020 18:15:06 info    [MainThread] asyncio_client._handle_event --- Received event "message" [/]
10-04-2020 18:15:06 info    [MainThread] asyncio_client.emit --- Emitting event "message" [/]
10-04-2020 18:15:06 info    [MainThread] asyncio_client._send_packet --- Sending packet MESSAGE data 2["message","{..}"]
10-04-2020 18:15:08 info    [MainThread] asyncio_client._receive_packet --- Received packet MESSAGE data 2["message","{..}"]
10-04-2020 18:15:11 info    [MainThread] asyncio_client._send_packet --- Sending packet PING data None
10-04-2020 18:15:11 info    [MainThread] asyncio_client._receive_packet --- Received packet PONG data None
10-04-2020 18:15:16 debug   [MainThread] __init__.tick --- sio.connected: True
10-04-2020 18:15:16 debug   [MainThread] __init__.tick --- sio.eio.ws.closed: False
10-04-2020 18:15:17 info    [MainThread] asyncio_client.emit --- Emitting event "message" [/]
10-04-2020 18:15:17 info    [MainThread] asyncio_client._send_packet --- Sending packet MESSAGE data 2["message","{..}"]
10-04-2020 18:15:17 info    [MainThread] asyncio_client.emit --- Emitting event "message" [/]
10-04-2020 18:15:17 info    [MainThread] asyncio_client._send_packet --- Sending packet MESSAGE data 2["message","{..}"]
10-04-2020 18:15:17 info    [MainThread] asyncio_client.emit --- Emitting event "message" [/]
10-04-2020 18:15:17 info    [MainThread] asyncio_client._send_packet --- Sending packet MESSAGE data 2["message","{..}"]
10-04-2020 18:15:17 info    [MainThread] asyncio_client.emit --- Emitting event "message" [/]
10-04-2020 18:15:17 info    [MainThread] asyncio_client._send_packet --- Sending packet MESSAGE data 2["message","{..}"]
10-04-2020 18:15:17 info    [MainThread] __init__.tick --- checked
10-04-2020 18:15:36 info    [MainThread] asyncio_client._send_packet --- Sending packet PING data None
10-04-2020 18:15:46 debug   [MainThread] __init__.tick --- sio.connected: True
10-04-2020 18:15:46 debug   [MainThread] __init__.tick --- sio.eio.ws.closed: True
10-04-2020 18:15:47 info    [MainThread] asyncio_client.emit --- Emitting event "message" [/]
10-04-2020 18:15:47 info    [MainThread] asyncio_client._send_packet --- Sending packet MESSAGE data 2["message","{..}"]
10-04-2020 18:15:47 warning [MainThread] http_websocket._send_frame --- websocket connection is closing.
10-04-2020 18:15:47 info    [MainThread] asyncio_client.emit --- Emitting event "message" [/]
10-04-2020 18:15:47 info    [MainThread] asyncio_client._send_packet --- Sending packet MESSAGE data 2["message","{..}"]
10-04-2020 18:15:47 warning [MainThread] http_websocket._send_frame --- websocket connection is closing.
10-04-2020 18:15:47 info    [MainThread] asyncio_client.emit --- Emitting event "message" [/]
10-04-2020 18:15:47 info    [MainThread] asyncio_client._send_packet --- Sending packet MESSAGE data 2["message","{..}"]
10-04-2020 18:15:47 warning [MainThread] http_websocket._send_frame --- websocket connection is closing.
10-04-2020 18:15:47 info    [MainThread] asyncio_client.emit --- Emitting event "message" [/]
10-04-2020 18:15:47 info    [MainThread] asyncio_client._send_packet --- Sending packet MESSAGE data 2["message","{..}"]
10-04-2020 18:15:47 info    [MainThread] __init__.tick --- checked
10-04-2020 18:15:47 warning [MainThread] http_websocket._send_frame --- websocket connection is closing.
10-04-2020 18:16:01 info    [MainThread] asyncio_client._ping_loop --- PONG response has not been received, aborting
10-04-2020 18:16:01 info    [MainThread] asyncio_client._ping_loop --- Exiting ping task
10-04-2020 18:16:01 info    [MainThread] asyncio_client._write_loop --- Exiting write loop task
10-04-2020 18:16:16 debug   [MainThread] __init__.tick --- sio.connected: True
10-04-2020 18:16:16 debug   [MainThread] __init__.tick --- sio.eio.ws.closed: True
10-04-2020 18:16:17 info    [MainThread] asyncio_client.emit --- Emitting event "message" [/]
10-04-2020 18:16:17 info    [MainThread] asyncio_client._send_packet --- Sending packet MESSAGE data 2["message","{..}"]
10-04-2020 18:16:17 info    [MainThread] asyncio_client.emit --- Emitting event "message" [/]
10-04-2020 18:16:17 info    [MainThread] asyncio_client._send_packet --- Sending packet MESSAGE data 2["message","{..}"]
10-04-2020 18:16:17 info    [MainThread] asyncio_client.emit --- Emitting event "message" [/]
10-04-2020 18:16:17 info    [MainThread] asyncio_client._send_packet --- Sending packet MESSAGE data 2["message","{..}"]
10-04-2020 18:16:17 info    [MainThread] asyncio_client.emit --- Emitting event "message" [/]
10-04-2020 18:16:17 info    [MainThread] asyncio_client._send_packet --- Sending packet MESSAGE data 2["message","{..}"]
10-04-2020 18:16:17 info    [MainThread] __init__.tick --- checked
10-04-2020 18:16:46 debug   [MainThread] __init__.tick --- sio.connected: True
10-04-2020 18:16:46 debug   [MainThread] __init__.tick --- sio.eio.ws.closed: True
10-04-2020 18:16:47 info    [MainThread] asyncio_client.emit --- Emitting event "message" [/]
10-04-2020 18:16:47 info    [MainThread] asyncio_client._send_packet --- Sending packet MESSAGE data 2["message","{..}"]
10-04-2020 18:16:47 info    [MainThread] asyncio_client.emit --- Emitting event "message" [/]
10-04-2020 18:16:47 info    [MainThread] asyncio_client._send_packet --- Sending packet MESSAGE data 2["message","{..}"]
10-04-2020 18:16:47 info    [MainThread] asyncio_client.emit --- Emitting event "message" [/]
10-04-2020 18:16:47 info    [MainThread] asyncio_client._send_packet --- Sending packet MESSAGE data 2["message","{..}"]
10-04-2020 18:16:47 info    [MainThread] asyncio_client.emit --- Emitting event "message" [/]
10-04-2020 18:16:47 info    [MainThread] asyncio_client._send_packet --- Sending packet MESSAGE data 2["message","{..}"]
10-04-2020 18:16:47 info    [MainThread] __init__.tick --- checked
```
</details>
