### ISSUE TITLE
Unclosed client session (aiohttp.client.ClientSession)

### ISSUE THREAD

**Issue by sebszyller** [miguelgrinberg/python-socketio#922]
It looks like the async client doesn't clean up properly after/before disconnecting from the server.
I'm running Flask wrapped with SocketIO on the backend, and I think this is the smallest reproducible code.

Client:
```python
import asyncio
import socketio


async def main():
    async_client = socketio.AsyncClient(logger=True, engineio_logger=True)
    server_address = "http://127.0.0.1:5000/"
    server_namespace = "/"

    await async_client.connect(server_address, namespaces=[server_namespace])

    await async_client.sleep(2)

    await async_client.disconnect()


if __name__ == "__main__":
    asyncio.run(main())
```

and server:
```python
app = Flask(__name__)
socketio = SocketIO(app)

@socketio.on('connect')
def test_connect(auth):
    emit('my response', {'data': 'Connected'})

@socketio.on('disconnect')
def test_disconnect():
    print('Client disconnected')

if __name__ == '__main__':
    socketio.run(app)
```

On the server side, connect and disconnect events are fine. However, the session is not closed properly and aiohttp gives a warning:
```bash
Attempting polling connection to http://127.0.0.1:5000/socket.io/?transport=polling&EIO=4
Polling connection accepted with {'sid': 'QCEoc5oKxKUvwbdyAAAA', 'upgrades': [], 'pingTimeout': 20000, 'pingInterval': 25000}
Engine.IO connection established
Sending packet MESSAGE data 0{}
Sending polling GET request to http://127.0.0.1:5000/socket.io/?transport=polling&EIO=4&sid=QCEoc5oKxKUvwbdyAAAA
Received packet MESSAGE data 0{"sid":"rNuPT0HhEJrCWzRdAAAB"}
Sending polling GET request to http://127.0.0.1:5000/socket.io/?transport=polling&EIO=4&sid=QCEoc5oKxKUvwbdyAAAA
Namespace / is connected
Sending packet MESSAGE data 1
Sending packet CLOSE data None
Engine.IO connection dropped
Exiting write loop task
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x10647a640>
```

I'm running MacOS 12.3 and these are the library versions.
```bash
flask                     2.0.2                    pypi_0    pypi
flask-socketio            5.1.1                    pypi_0    pypi
python-socketio           5.5.2                    pypi_0    pypi
```
Why is this warning triggering?

**Comment by miguelgrinberg** [comment]
What version of python-engineio do you have? This was fixed recently ([https://github.com/miguelgrinberg/python-engineio/issues/272), try the latest release of this package.

**Comment by sebszyller** [comment]
I have python-engineio 4.3.1. I've updated it to 4.3.2 (the latest version that pip installs) and the issue remains.

**Comment by miguelgrinberg** [comment]
I can reproduce with python-engineio 4.3.2. Output using your code:

```
Attempting polling connection to http://127.0.0.1:5000/socket.io/?transport=polling&EIO=4
Polling connection accepted with {'sid': 'ESJEVlQeDy_99nbiAAAA', 'upgrades': ['websocket'], 'pingTimeout': 20000, 'pingInterval': 25000}
Engine.IO connection established
Sending packet MESSAGE data 0
Attempting WebSocket upgrade to ws://127.0.0.1:5000/socket.io/?transport=websocket&EIO=4
WebSocket upgrade was successful
Received packet NOOP data
Received packet MESSAGE data 2["my response",{"data":"Connected"}]
Received event "my response" [/]
Received packet MESSAGE data 0{"sid":"fItJTxACcF7EzySWAAAB"}
Namespace / is connected
Sending packet MESSAGE data 1
Sending packet CLOSE data None
Engine.IO connection dropped
Write loop: WebSocket connection was closed, aborting
Exiting write loop task
Waiting for write loop task to end
Exiting read loop task
```

**Comment by sebszyller** [comment]
I did more digging around and it turns out that I had an outdated version of `gevent`.
I don't know what's the discrepancy between the versions exactly but things work as intended now.
